"""
Django settings for mirador_illari project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")

DEBUG = os.getenv(
    "DJANGO_DEBUG",
    "False",
).lower() in {"1", "true", "yes", "on"}

SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

if not SECRET_KEY:
    raise RuntimeError(
        "Debes configurar DJANGO_SECRET_KEY en el archivo .env."
    )

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        "DJANGO_ALLOWED_HOSTS",
        "127.0.0.1,localhost",
    ).split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_ckeditor_5',
    'principal',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mirador_illari.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'principal' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'principal.context_processors.sitio_context',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mirador_illari.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "mirador_illari"),
        "USER": os.getenv("DB_USER", "illariuser"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-ec'

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/



STATIC_URL = '/static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    "site_title": "Mirador Illari",
    "site_header": "Centro Turístico Mirador Illari",
    "site_brand": "Mirador Illari",
    "welcome_sign": "Bienvenido al Panel Administrativo",
    "copyright": "Mirador Illari",

    # Configuración de logotipos (Rutas relativas a /static/)
    "site_logo": "img/logo.jpeg",        # Logo para el sidebar
    "login_logo": "img/logo.jpeg",       # Logo para el login
    "favicon": "img/logo.jpeg",          # Icono de la pestaña del navegador
    "theme": "darkly",                   # Estilo oscuro del panel


    # AGREGA ESTA SECCIÓN PARA EL ORDEN (1-6):
        # ORDENAMIENTO CORRECTO DE LA BARRA LATERAL EN JAZZMIN:
    "order_with_respect_to": [
        "auth.user",                           # Mueve Usuarios arriba si deseas mantenerlo al inicio
        "principal.carruselinicio",            # 1. Carrusel de Inicio
        "principal.contenidoinicio",           # 2. Textos de Página de Inicio
        "principal.informacioninstitucional",  # 3. Información Institucional
        "principal.valor",                     # 4. Valores Institucionales
        "principal.servicioturistico",         # 5. Servicios Turísticos
        "principal.eventonovedad",             # 6. Eventos y Novedades
        "principal.galeriamultimedia",         # 7. Galería Multimedia
        "principal.contacto",                  # 8. Contacto
        "principal.preguntafrecuente",         # 9. Preguntas Frecuentes
    ],

     "custom_css": "css/custom_admin.css",
}

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'

CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": [
            "heading",
            "|",
            "bold",
            "italic",
            "underline",
            "link",
            "bulletedList",
            "numberedList",
            "|",
            "insertTable",
            "blockQuote",
            "|",
            "undo",
            "redo",
        ]
    }
}

STATIC_ROOT = BASE_DIR / "staticfiles"

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
GEMINI_MODEL_NAME = os.getenv(
    "GEMINI_MODEL_NAME",
    "gemini-3.6-flash"
)
GEMINI_API_ENDPOINT = os.getenv("GEMINI_API_ENDPOINT", "")

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True