# Generated by Django 6.0.6 on 2026-07-06 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventonovedad',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='galeriamultimedia',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='preguntafrecuente',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='servicioturistico',
            name='usuario',
        ),
    ]
