# Generated by Django 6.0.6 on 2026-07-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_remove_eventonovedad_usuario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventonovedad',
            options={'verbose_name': 'Evento o Novedad', 'verbose_name_plural': 'Eventos y Novedades'},
        ),
        migrations.AlterModelOptions(
            name='galeriamultimedia',
            options={'verbose_name': 'Galería', 'verbose_name_plural': 'Galería Multimedia'},
        ),
        migrations.AlterModelOptions(
            name='informacioninstitucional',
            options={'verbose_name': 'Información Institucional', 'verbose_name_plural': 'Información Institucional'},
        ),
        migrations.AlterModelOptions(
            name='preguntafrecuente',
            options={'verbose_name': 'Pregunta Frecuente', 'verbose_name_plural': 'Preguntas Frecuentes'},
        ),
        migrations.AlterModelOptions(
            name='servicioturistico',
            options={'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AlterField(
            model_name='eventonovedad',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='eventonovedad',
            name='contenido',
            field=models.TextField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='eventonovedad',
            name='fecha_evento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del evento'),
        ),
        migrations.AlterField(
            model_name='eventonovedad',
            name='fecha_publicacion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='eventonovedad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='eventonovedad',
            name='tipo',
            field=models.CharField(max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='eventonovedad',
            name='titulo',
            field=models.CharField(max_length=150, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='galeriamultimedia',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='galeriamultimedia',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='galeriamultimedia',
            name='fecha_subida',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de subida'),
        ),
        migrations.AlterField(
            model_name='galeriamultimedia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='galeria/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='galeriamultimedia',
            name='titulo',
            field=models.CharField(max_length=150, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='informacioninstitucional',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='informacioninstitucional',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='informacioninstitucional',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='informacioninstitucional',
            name='eslogan',
            field=models.CharField(blank=True, max_length=150, verbose_name='Eslogan'),
        ),
        migrations.AlterField(
            model_name='informacioninstitucional',
            name='historia',
            field=models.TextField(blank=True, verbose_name='Historia'),
        ),
        migrations.AlterField(
            model_name='informacioninstitucional',
            name='horarios_atencion',
            field=models.CharField(blank=True, max_length=150, verbose_name='Horarios de atención'),
        ),
        migrations.AlterField(
            model_name='informacioninstitucional',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='informacioninstitucional',
            name='mision',
            field=models.TextField(blank=True, verbose_name='Misión'),
        ),
        migrations.AlterField(
            model_name='informacioninstitucional',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='informacioninstitucional',
            name='titulo',
            field=models.CharField(max_length=150, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='informacioninstitucional',
            name='vision',
            field=models.TextField(blank=True, verbose_name='Visión'),
        ),
        migrations.AlterField(
            model_name='informacioninstitucional',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='preguntafrecuente',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='preguntafrecuente',
            name='pregunta',
            field=models.TextField(verbose_name='Pregunta'),
        ),
        migrations.AlterField(
            model_name='preguntafrecuente',
            name='respuesta',
            field=models.TextField(verbose_name='Respuesta'),
        ),
        migrations.AlterField(
            model_name='servicioturistico',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='servicioturistico',
            name='capacidad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Capacidad'),
        ),
        migrations.AlterField(
            model_name='servicioturistico',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='servicioturistico',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='servicios/', verbose_name='Imagen principal'),
        ),
        migrations.AlterField(
            model_name='servicioturistico',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre del servicio'),
        ),
        migrations.AlterField(
            model_name='servicioturistico',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio ($)'),
        ),
        migrations.AlterField(
            model_name='servicioturistico',
            name='tipo',
            field=models.CharField(max_length=50, verbose_name='Tipo'),
        ),
    ]
