# Generated by Django 6.0.6 on 2026-07-11 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_alter_eventonovedad_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeriamultimedia',
            options={'verbose_name': 'Elemento de Galería', 'verbose_name_plural': 'Galería Multimedia'},
        ),
        migrations.AlterModelOptions(
            name='servicioturistico',
            options={'verbose_name': 'Servicio Turístico', 'verbose_name_plural': 'Servicios Turísticos'},
        ),
        migrations.AddField(
            model_name='eventonovedad',
            name='id_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galeriamultimedia',
            name='id_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informacioninstitucional',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿Mostrar en la Web pública?'),
        ),
        migrations.AddField(
            model_name='informacioninstitucional',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='informacioninstitucional',
            name='id_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informacioninstitucional',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='informacioninstitucional',
            name='mapa_embed_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de Google Maps (Embed)'),
        ),
        migrations.AddField(
            model_name='informacioninstitucional',
            name='tiktok_url',
            field=models.URLField(blank=True, null=True, verbose_name='TikTok URL'),
        ),
        migrations.AddField(
            model_name='informacioninstitucional',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube URL'),
        ),
        migrations.AddField(
            model_name='preguntafrecuente',
            name='id_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicioturistico',
            name='id_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventonovedad',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿Publicación Activa?'),
        ),
        migrations.AlterField(
            model_name='eventonovedad',
            name='contenido',
            field=models.TextField(verbose_name='Contenido / Detalle'),
        ),
        migrations.AlterField(
            model_name='eventonovedad',
            name='fecha_evento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del Evento'),
        ),
        migrations.AlterField(
            model_name='eventonovedad',
            name='fecha_publicacion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Publicación'),
        ),
        migrations.AlterField(
            model_name='eventonovedad',
            name='imagen',
            field=models.ImageField(default=1, upload_to='eventos/', verbose_name='Imagen Publicitaria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventonovedad',
            name='tipo',
            field=models.CharField(max_length=100, verbose_name='Tipo de Aviso'),
        ),
        migrations.AlterField(
            model_name='eventonovedad',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título del Evento'),
        ),
        migrations.AlterField(
            model_name='galeriamultimedia',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿Visible en Galería?'),
        ),
        migrations.AlterField(
            model_name='galeriamultimedia',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción Corta'),
        ),
        migrations.AlterField(
            model_name='galeriamultimedia',
            name='fecha_subida',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Subida'),
        ),
        migrations.AlterField(
            model_name='galeriamultimedia',
            name='imagen',
            field=models.ImageField(default=1, upload_to='galeria/', verbose_name='Archivo de Imagen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='galeriamultimedia',
            name='titulo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='informacioninstitucional',
            name='correo',
            field=models.EmailField(max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='informacioninstitucional',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción General'),
        ),
        migrations.AlterField(
            model_name='informacioninstitucional',
            name='direccion',
            field=models.CharField(max_length=250, verbose_name='Dirección Física'),
        ),
        migrations.AlterField(
            model_name='informacioninstitucional',
            name='eslogan',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Eslogan'),
        ),
        migrations.AlterField(
            model_name='informacioninstitucional',
            name='historia',
            field=models.TextField(blank=True, null=True, verbose_name='Historia'),
        ),
        migrations.AlterField(
            model_name='informacioninstitucional',
            name='horarios_atencion',
            field=models.CharField(max_length=200, verbose_name='Horarios de Atención'),
        ),
        migrations.AlterField(
            model_name='informacioninstitucional',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='institucional/', verbose_name='Logo Institucional'),
        ),
        migrations.AlterField(
            model_name='informacioninstitucional',
            name='mision',
            field=models.TextField(verbose_name='Misión'),
        ),
        migrations.AlterField(
            model_name='informacioninstitucional',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Fijo'),
        ),
        migrations.AlterField(
            model_name='informacioninstitucional',
            name='titulo',
            field=models.CharField(max_length=150, verbose_name='Título Institucional'),
        ),
        migrations.AlterField(
            model_name='informacioninstitucional',
            name='vision',
            field=models.TextField(verbose_name='Visión'),
        ),
        migrations.AlterField(
            model_name='informacioninstitucional',
            name='whatsapp',
            field=models.CharField(max_length=20, verbose_name='Número de WhatsApp'),
        ),
        migrations.AlterField(
            model_name='preguntafrecuente',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿Activa en la Base del Chatbot?'),
        ),
        migrations.AlterField(
            model_name='preguntafrecuente',
            name='pregunta',
            field=models.TextField(verbose_name='Pregunta del Usuario'),
        ),
        migrations.AlterField(
            model_name='preguntafrecuente',
            name='respuesta',
            field=models.TextField(verbose_name='Respuesta del Chatbot'),
        ),
        migrations.AlterField(
            model_name='servicioturistico',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿Servicio Activo / Visible?'),
        ),
        migrations.AlterField(
            model_name='servicioturistico',
            name='capacidad',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidad Máxima'),
        ),
        migrations.AlterField(
            model_name='servicioturistico',
            name='imagen_principal',
            field=models.ImageField(default=1, upload_to='servicios/', verbose_name='Imagen Principal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicioturistico',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre del Servicio'),
        ),
        migrations.AlterField(
            model_name='servicioturistico',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Precio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicioturistico',
            name='tipo',
            field=models.CharField(max_length=100, verbose_name='Tipo (Hospedaje, Camping, etc.)'),
        ),
        migrations.CreateModel(
            name='CarruselInicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Título (Opcional)')),
                ('subtitulo', models.CharField(blank=True, max_length=250, null=True, verbose_name='Subtítulo / Descripción (Opcional)')),
                ('imagen', models.ImageField(upload_to='carrusel/', verbose_name='Imagen de Fondo (Recomendado 1920x1080)')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de aparición')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Mostrar en la Portada?')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
            ],
            options={
                'verbose_name': 'Imagen de Carrusel',
                'verbose_name_plural': 'Carrusel de Inicio',
                'ordering': ['orden'],
            },
        ),
    ]
