# Generated by Django 6.0.6 on 2026-07-11 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_alter_carruselinicio_id_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventonovedad',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
        ),
        migrations.AlterField(
            model_name='galeriamultimedia',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
        ),
        migrations.AlterField(
            model_name='informacioninstitucional',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
        ),
        migrations.AlterField(
            model_name='preguntafrecuente',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
        ),
        migrations.AlterField(
            model_name='servicioturistico',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
        ),
        migrations.CreateModel(
            name='ContenidoInicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='carrusel/', verbose_name='Imagen de Fondo (Recomendado 1920x1080)')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de aparición')),
                ('activo_imagen', models.BooleanField(default=True, verbose_name='¿Mostrar esta FOTO en el Carrusel?')),
                ('activo_informacion', models.BooleanField(default=True, verbose_name='¿Mostrar los TEXTOS y TARJETAS en la Web?')),
                ('hero_titulo', models.CharField(default='Bienvenidos al Centro Turístico Mirador Illari', max_length=200, verbose_name='Título del Banner')),
                ('hero_subtitulo', models.CharField(default='Naturaleza, aventura y cultura local en un solo lugar.', max_length=250, verbose_name='Subtítulo del Banner')),
                ('atractivo_1_titulo', models.CharField(default='🌄 Paisajes', max_length=100, verbose_name='Título Tarjeta 1')),
                ('atractivo_1_desc', models.TextField(default='Espacios naturales ideales para fotografías y descanso.', verbose_name='Descripción Tarjeta 1')),
                ('atractivo_2_titulo', models.CharField(default='🥾 Aventura', max_length=100, verbose_name='Título Tarjeta 2')),
                ('atractivo_2_desc', models.TextField(default='Actividades al aire libre para vivir una experiencia diferente.', verbose_name='Descripción Tarjeta 2')),
                ('atractivo_3_titulo', models.CharField(default='🌿 Cultura local', max_length=100, verbose_name='Título Tarjeta 3')),
                ('atractivo_3_desc', models.TextField(default='Un lugar que promueve el turismo comunitario y la identidad local.', verbose_name='Descripción Tarjeta 3')),
                ('atractivo_4_titulo', models.CharField(default='🤝 Atención', max_length=100, verbose_name='Título Tarjeta 4')),
                ('atractivo_4_desc', models.TextField(default='Información clara para que los visitantes planifiquen su visita.', verbose_name='Descripción Tarjeta 4')),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
            ],
            options={
                'verbose_name': 'Contenido de Inicio',
                'verbose_name_plural': 'Módulo de Página de Inicio',
                'ordering': ['orden'],
            },
        ),
        migrations.DeleteModel(
            name='CarruselInicio',
        ),
    ]
