# Generated by Django 6.0.6 on 2026-07-11 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_alter_eventonovedad_id_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenidoinicio',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='eventonovedad',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='galeriamultimedia',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='informacioninstitucional',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='preguntafrecuente',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='servicioturistico',
            name='id_usuario',
        ),
    ]
