# Generated by Django 6.0.6 on 2026-07-11 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_remove_contenidoinicio_id_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenidoinicio',
            options={'verbose_name': 'Texto de Inicio', 'verbose_name_plural': '2. Textos de Página de Inicio'},
        ),
        migrations.RemoveField(
            model_name='contenidoinicio',
            name='activo_imagen',
        ),
        migrations.RemoveField(
            model_name='contenidoinicio',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='contenidoinicio',
            name='orden',
        ),
        migrations.AddField(
            model_name='contenidoinicio',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
        ),
        migrations.AddField(
            model_name='eventonovedad',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
        ),
        migrations.AddField(
            model_name='galeriamultimedia',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
        ),
        migrations.AddField(
            model_name='informacioninstitucional',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
        ),
        migrations.AddField(
            model_name='preguntafrecuente',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
        ),
        migrations.AddField(
            model_name='servicioturistico',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
        ),
        migrations.AlterField(
            model_name='contenidoinicio',
            name='activo_informacion',
            field=models.BooleanField(default=True, verbose_name='¿Mostrar estos textos en la Web?'),
        ),
        migrations.CreateModel(
            name='CarruselInicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='carrusel/', verbose_name='Imagen de Fondo (Recomendado 1920x1080)')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de aparición')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Mostrar esta foto en el Carrusel?')),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
            ],
            options={
                'verbose_name': 'Imagen de Carrusel',
                'verbose_name_plural': '1. Carrusel de Inicio (Solo Fotos)',
                'ordering': ['orden'],
            },
        ),
    ]
