# Generated by Django 6.0.6 on 2026-07-11 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_alter_contenidoinicio_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventonovedad',
            options={'verbose_name': 'Evento o Novedad', 'verbose_name_plural': '5. Eventos y Novedades'},
        ),
        migrations.AlterModelOptions(
            name='galeriamultimedia',
            options={'verbose_name': 'Elemento de Galería', 'verbose_name_plural': '6. Galería Multimedia'},
        ),
        migrations.AlterModelOptions(
            name='informacioninstitucional',
            options={'verbose_name': 'Información Institucional', 'verbose_name_plural': '3. Información Institucional'},
        ),
        migrations.AlterModelOptions(
            name='preguntafrecuente',
            options={'verbose_name': 'Pregunta Frecuente', 'verbose_name_plural': '7. Preguntas Frecuentes'},
        ),
        migrations.AlterModelOptions(
            name='servicioturistico',
            options={'verbose_name': 'Servicio Turístico', 'verbose_name_plural': '4. Servicios Turísticos'},
        ),
        migrations.AlterField(
            model_name='contenidoinicio',
            name='atractivo_2_desc',
            field=models.TextField(default='Actividades al aire libre para vivir una experience diferente.', verbose_name='Descripción Tarjeta 2'),
        ),
    ]
