# Generated by Django 6.0.6 on 2026-07-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_alter_eventonovedad_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_bienvenida', models.CharField(default='Bienvenidos al Centro Turístico Mirador Illari', help_text='Título que aparece en el banner principal', max_length=200, verbose_name='Título Principal')),
                ('subtitulo_eslogan', models.CharField(default='Naturaleza, aventura y cultura local en un solo lugar.', help_text='Frase descriptiva bajo el título', max_length=300, verbose_name='Subtítulo/Eslogan')),
                ('texto_boton_cta', models.CharField(default='Conocer Más', help_text='Texto del botón de llamada a acción', max_length=100, verbose_name='Texto del Botón CTA')),
                ('enlace_boton', models.CharField(default='#servicios', help_text='URL o ancla interna (#servicios, /galeria, etc.)', max_length=500, verbose_name='Enlace del Botón')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Mostrar en la Web?')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Contenido Hero',
                'verbose_name_plural': '2. 🎯 Sección Hero (Textos Principales)',
            },
        ),
        migrations.RemoveField(
            model_name='contenidoinicio',
            name='id_usuario',
        ),
        migrations.CreateModel(
            name='CarruselPortada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_slide', models.CharField(blank=True, help_text='Opcional: Texto sobre la imagen del carrusel', max_length=200, null=True, verbose_name='Título del Slide')),
                ('imagen', models.ImageField(help_text='Recomendado: 1920x1080px (JPG/PNG)', upload_to='carrusel/', verbose_name='Imagen del Slide')),
                ('orden', models.PositiveIntegerField(default=0, help_text='0=Primero, 1=Segundo, etc. (ordena ascendente)', verbose_name='Orden de Aparición')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Mostrar en la Web?')),
            ],
            options={
                'verbose_name': 'Slide del Carrusel',
                'verbose_name_plural': '1. 🎠 Carrusel de Portada',
                'ordering': ['orden'],
                'indexes': [models.Index(fields=['activo', 'orden'], name='principal_c_activo_d5c892_idx')],
            },
        ),
        migrations.CreateModel(
            name='TarjetaAtractivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono_emoji', models.CharField(help_text='Ej: 🌄, 🥾, 🌿, 🤝, ⛰️, etc.', max_length=10, verbose_name='Icono/Emoji')),
                ('titulo_atractivo', models.CharField(help_text='Nombre breve del atractivo (Ej: Paisajes)', max_length=100, verbose_name='Título del Atractivo')),
                ('descripcion_corta', models.TextField(help_text='Máximo 300 caracteres describiendo el atractivo', max_length=300, verbose_name='Descripción Corta')),
                ('orden', models.PositiveIntegerField(default=0, help_text='0=Primero, 1=Segundo, etc.', verbose_name='Orden de Aparición')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Mostrar en la Web?')),
            ],
            options={
                'verbose_name': 'Tarjeta de Atractivo',
                'verbose_name_plural': '3. ✨ Tarjetas de Atractivos',
                'ordering': ['orden'],
                'indexes': [models.Index(fields=['activo', 'orden'], name='principal_t_activo_5f41a8_idx')],
            },
        ),
        migrations.DeleteModel(
            name='CarruselInicio',
        ),
        migrations.DeleteModel(
            name='ContenidoInicio',
        ),
    ]
