# Generated by Django 6.0.6 on 2026-07-12 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_contenidohero_remove_contenidoinicio_id_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarruselInicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='carrusel/', verbose_name='Imagen de Fondo (Recomendado 1920x1080)')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de aparición')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Mostrar esta foto en el Carrusel?')),
            ],
            options={
                'verbose_name': 'Imagen de Carrusel',
                'verbose_name_plural': '1. Carrusel de Inicio (Solo Fotos)',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ContenidoInicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo_informacion', models.BooleanField(default=True, verbose_name='¿Mostrar estos textos en la Web?')),
                ('hero_titulo', models.CharField(default='Bienvenidos al Centro Turístico Mirador Illari', max_length=200, verbose_name='Título del Banner')),
                ('hero_subtitulo', models.CharField(default='Naturaleza, aventura y cultura local en un solo lugar.', max_length=250, verbose_name='Subtítulo del Banner')),
                ('atractivo_1_titulo', models.CharField(default='🌄 Paisajes', max_length=100, verbose_name='Título Tarjeta 1')),
                ('atractivo_1_desc', models.TextField(default='Espacios naturales ideales para fotografías y descanso.', verbose_name='Descripción Tarjeta 1')),
                ('atractivo_2_titulo', models.CharField(default='🥾 Aventura', max_length=100, verbose_name='Título Tarjeta 2')),
                ('atractivo_2_desc', models.TextField(default='Actividades al aire libre para vivir una experience diferente.', verbose_name='Descripción Tarjeta 2')),
                ('atractivo_3_titulo', models.CharField(default='🌿 Cultura local', max_length=100, verbose_name='Título Tarjeta 3')),
                ('atractivo_3_desc', models.TextField(default='Un lugar que promueve el turismo comunitario y la identidad local.', verbose_name='Descripción Tarjeta 3')),
                ('atractivo_4_titulo', models.CharField(default='🤝 Atención', max_length=100, verbose_name='Título Tarjeta 4')),
                ('atractivo_4_desc', models.TextField(default='Información clara para que los visitantes planifiquen su visita.', verbose_name='Descripción Tarjeta 4')),
            ],
            options={
                'verbose_name': 'Texto de Inicio',
                'verbose_name_plural': '2. Textos de Página de Inicio',
            },
        ),
        migrations.RemoveIndex(
            model_name='carruselportada',
            name='principal_c_activo_d5c892_idx',
        ),
        migrations.DeleteModel(
            name='CarruselPortada',
        ),
        migrations.DeleteModel(
            name='ContenidoHero',
        ),
        migrations.RemoveIndex(
            model_name='tarjetaatractivo',
            name='principal_t_activo_5f41a8_idx',
        ),
        migrations.DeleteModel(
            name='TarjetaAtractivo',
        ),
        migrations.AddField(
            model_name='carruselinicio',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
        ),
        migrations.AddField(
            model_name='contenidoinicio',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
        ),
    ]
