# Generated by Django 6.0.6 on 2026-07-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0011_carruselinicio_contenidoinicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicioturistico',
            name='precio',
        ),
        migrations.AddField(
            model_name='servicioturistico',
            name='precio_adulto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Adulto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicioturistico',
            name='precio_niño',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Niño'),
        ),
        migrations.AddField(
            model_name='servicioturistico',
            name='precio_tercera_edad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Tercera Edad'),
        ),
    ]
