# Generated by Django 6.0.6 on 2026-07-12 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_remove_servicioturistico_precio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Valor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Nombre del Valor')),
                ('descripcion', models.TextField(verbose_name='Descripción del Valor')),
                ('icono_emoji', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ícono (Emoji)')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de aparición')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Mostrar este valor?')),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
            ],
            options={
                'verbose_name': 'Valor Institucional',
                'verbose_name_plural': '8. Valores Institucionales',
                'ordering': ['orden'],
            },
        ),
    ]
