# Generated by Django 6.0.6 on 2026-07-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0013_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacioninstitucional',
            name='proposito',
            field=models.TextField(blank=True, null=True, verbose_name='Propósito Institucional'),
        ),
    ]
