# Generated by Django 6.0.6 on 2026-07-12 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0014_informacioninstitucional_proposito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacioninstitucional',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='informacioninstitucional',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='informacioninstitucional',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='informacioninstitucional',
            name='horarios_atencion',
        ),
        migrations.RemoveField(
            model_name='informacioninstitucional',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='informacioninstitucional',
            name='mapa_embed_url',
        ),
        migrations.RemoveField(
            model_name='informacioninstitucional',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='informacioninstitucional',
            name='tiktok_url',
        ),
        migrations.RemoveField(
            model_name='informacioninstitucional',
            name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='informacioninstitucional',
            name='youtube_url',
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=250, verbose_name='Dirección Física')),
                ('mapa_embed_url', models.URLField(blank=True, null=True, verbose_name='URL de Google Maps (Embed)')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='Número de WhatsApp')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Fijo')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('horarios_atencion', models.CharField(max_length=200, verbose_name='Horarios de Atención')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook URL')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='Instagram URL')),
                ('tiktok_url', models.URLField(blank=True, null=True, verbose_name='TikTok URL')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='YouTube URL')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Mostrar en la Web pública?')),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': '4. Contacto',
            },
        ),
    ]
