# Generated by Django 6.0.6 on 2026-07-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0015_remove_informacioninstitucional_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidoinicio',
            name='atractivo_1_activo',
            field=models.BooleanField(default=True, verbose_name='Mostrar tarjeta Paisajes'),
        ),
        migrations.AddField(
            model_name='contenidoinicio',
            name='atractivo_2_activo',
            field=models.BooleanField(default=True, verbose_name='Mostrar tarjeta Aventura'),
        ),
        migrations.AddField(
            model_name='contenidoinicio',
            name='atractivo_3_activo',
            field=models.BooleanField(default=True, verbose_name='Mostrar tarjeta Cultura local'),
        ),
        migrations.AddField(
            model_name='contenidoinicio',
            name='atractivo_4_activo',
            field=models.BooleanField(default=True, verbose_name='Mostrar tarjeta Atención'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='mapa_embed_url',
            field=models.URLField(blank=True, help_text='Pega cualquier enlace de Google Maps o Google Maps App. Se convertirá automáticamente en un mapa incrustado.', null=True, verbose_name='Enlace de Google Maps'),
        ),
        migrations.AlterField(
            model_name='contenidoinicio',
            name='atractivo_2_desc',
            field=models.TextField(default='Actividades al aire libre para vivir una experiencia diferente.', verbose_name='Descripción Tarjeta 2'),
        ),
    ]
