# Generated by Django 6.0.6 on 2026-07-12 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0016_contenidoinicio_atractivo_1_activo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtractivoInicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título de Atractivo')),
                ('descripcion', models.TextField(verbose_name='Descripción del Atractivo')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Mostrar este atractivo?')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de aparición')),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atractivos', to='principal.contenidoinicio', verbose_name='Contenido de Inicio')),
            ],
            options={
                'verbose_name': 'Atractivo de Inicio',
                'verbose_name_plural': 'Atractivos de Inicio',
                'ordering': ['orden'],
            },
        ),
    ]
