# Generated by Django 6.0.6 on 2026-07-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0018_add_default_valores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'verbose_name': 'Contacto', 'verbose_name_plural': '8. Contacto'},
        ),
        migrations.AlterModelOptions(
            name='eventonovedad',
            options={'verbose_name': 'Evento o Novedad', 'verbose_name_plural': '6. Eventos y Novedades'},
        ),
        migrations.AlterModelOptions(
            name='galeriamultimedia',
            options={'verbose_name': 'Elemento de Galería', 'verbose_name_plural': '7. Galería Multimedia'},
        ),
        migrations.AlterModelOptions(
            name='preguntafrecuente',
            options={'verbose_name': 'Pregunta Frecuente', 'verbose_name_plural': '9. Preguntas Frecuentes'},
        ),
        migrations.AlterModelOptions(
            name='servicioturistico',
            options={'verbose_name': 'Servicio Turístico', 'verbose_name_plural': '5. Servicios Turísticos'},
        ),
        migrations.AlterModelOptions(
            name='valor',
            options={'ordering': ['orden'], 'verbose_name': 'Valor Institucional', 'verbose_name_plural': '4. Valores Institucionales'},
        ),
        migrations.AddField(
            model_name='contenidoinicio',
            name='atractivos_descripcion',
            field=models.TextField(blank=True, default='Explora los lugares y experiencias que hacen único al Mirador Illari.', verbose_name='Descripción de sección de atractivos'),
        ),
        migrations.AddField(
            model_name='contenidoinicio',
            name='atractivos_titulo',
            field=models.CharField(blank=True, default='Nuestros atractivos', max_length=100, verbose_name='Título de sección de atractivos'),
        ),
        migrations.AddField(
            model_name='contenidoinicio',
            name='hero_boton_texto',
            field=models.CharField(blank=True, default='Planifica tu visita', max_length=100, verbose_name='Texto del botón del banner'),
        ),
        migrations.AddField(
            model_name='contenidoinicio',
            name='hero_boton_url',
            field=models.CharField(blank=True, default='/contacto/', max_length=500, verbose_name='Enlace del botón del banner'),
        ),
        migrations.AddField(
            model_name='informacioninstitucional',
            name='contacto_titulo',
            field=models.CharField(blank=True, default='Contacto', max_length=100, verbose_name='Título de contacto'),
        ),
        migrations.AddField(
            model_name='informacioninstitucional',
            name='eventos_titulo',
            field=models.CharField(blank=True, default='Eventos y Novedades', max_length=100, verbose_name='Título de eventos'),
        ),
        migrations.AddField(
            model_name='informacioninstitucional',
            name='galeria_titulo',
            field=models.CharField(blank=True, default='Galería Multimedia', max_length=100, verbose_name='Título de galería'),
        ),
        migrations.AddField(
            model_name='informacioninstitucional',
            name='nosotros_eyebrow',
            field=models.CharField(blank=True, default='Quiénes somos', max_length=100, verbose_name='Etiqueta de sección Nosotros'),
        ),
        migrations.AddField(
            model_name='informacioninstitucional',
            name='proposito_titulo',
            field=models.CharField(blank=True, default='Nuestro propósito', max_length=100, verbose_name='Título de propósito'),
        ),
        migrations.AddField(
            model_name='informacioninstitucional',
            name='servicios_titulo',
            field=models.CharField(blank=True, default='Servicios Turísticos', max_length=100, verbose_name='Título de servicios'),
        ),
        migrations.AddField(
            model_name='informacioninstitucional',
            name='valores_titulo',
            field=models.CharField(blank=True, default='Nuestros Valores', max_length=100, verbose_name='Título de valores'),
        ),
        migrations.AlterField(
            model_name='contenidoinicio',
            name='atractivo_1_desc',
            field=models.TextField(blank=True, verbose_name='Descripción Tarjeta 1'),
        ),
        migrations.AlterField(
            model_name='contenidoinicio',
            name='atractivo_1_titulo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Título Tarjeta 1'),
        ),
        migrations.AlterField(
            model_name='contenidoinicio',
            name='atractivo_2_desc',
            field=models.TextField(blank=True, verbose_name='Descripción Tarjeta 2'),
        ),
        migrations.AlterField(
            model_name='contenidoinicio',
            name='atractivo_2_titulo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Título Tarjeta 2'),
        ),
        migrations.AlterField(
            model_name='contenidoinicio',
            name='atractivo_3_desc',
            field=models.TextField(blank=True, verbose_name='Descripción Tarjeta 3'),
        ),
        migrations.AlterField(
            model_name='contenidoinicio',
            name='atractivo_3_titulo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Título Tarjeta 3'),
        ),
        migrations.AlterField(
            model_name='contenidoinicio',
            name='atractivo_4_desc',
            field=models.TextField(blank=True, verbose_name='Descripción Tarjeta 4'),
        ),
        migrations.AlterField(
            model_name='contenidoinicio',
            name='atractivo_4_titulo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Título Tarjeta 4'),
        ),
        migrations.AlterField(
            model_name='contenidoinicio',
            name='hero_subtitulo',
            field=models.CharField(blank=True, max_length=250, verbose_name='Subtítulo del Banner'),
        ),
        migrations.AlterField(
            model_name='contenidoinicio',
            name='hero_titulo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Título del Banner'),
        ),
        migrations.DeleteModel(
            name='AtractivoInicio',
        ),
    ]
