# Generated by Django 6.0.6 on 2026-07-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0019_alter_contacto_options_alter_eventonovedad_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacioninstitucional',
            name='chatbot_enviar_texto',
            field=models.CharField(blank=True, default='Enviar', max_length=50, verbose_name='Texto del botón Enviar'),
        ),
        migrations.AddField(
            model_name='informacioninstitucional',
            name='chatbot_intro',
            field=models.TextField(blank=True, default='Hola 👋 Soy el chatbot del Mirador Illari. ¿En qué puedo ayudarte?', verbose_name='Texto de bienvenida del chatbot'),
        ),
        migrations.AddField(
            model_name='informacioninstitucional',
            name='chatbot_opciones_etiqueta',
            field=models.CharField(blank=True, default='Opciones rápidas', max_length=150, verbose_name='Etiqueta de opciones rápidas'),
        ),
        migrations.AddField(
            model_name='informacioninstitucional',
            name='chatbot_placeholder',
            field=models.CharField(blank=True, default='Escribe tu mensaje...', max_length=150, verbose_name='Texto del placeholder de entrada'),
        ),
        migrations.AddField(
            model_name='informacioninstitucional',
            name='chatbot_respuesta_predeterminada',
            field=models.TextField(blank=True, default='Gracias por tu mensaje. Para más información puedes revisar las opciones rápidas o contactarnos por WhatsApp.', verbose_name='Respuesta predeterminada del chatbot'),
        ),
        migrations.AddField(
            model_name='informacioninstitucional',
            name='chatbot_titulo',
            field=models.CharField(blank=True, default='Chatbot Mirador Illari', max_length=150, verbose_name='Título del Chatbot'),
        ),
    ]
