# Generated by Django 6.0.6 on 2026-07-18 17:15

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0020_informacioninstitucional_chatbot_enviar_texto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenidoinicio',
            name='atractivo_1_desc',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Descripción Tarjeta 1'),
        ),
        migrations.AlterField(
            model_name='contenidoinicio',
            name='atractivo_2_desc',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Descripción Tarjeta 2'),
        ),
        migrations.AlterField(
            model_name='contenidoinicio',
            name='atractivo_3_desc',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Descripción Tarjeta 3'),
        ),
        migrations.AlterField(
            model_name='contenidoinicio',
            name='atractivo_4_desc',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Descripción Tarjeta 4'),
        ),
        migrations.AlterField(
            model_name='contenidoinicio',
            name='atractivos_descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='Explora los lugares y experiencias que hacen único al Mirador Illari.', verbose_name='Descripción de sección de atractivos'),
        ),
        migrations.AlterField(
            model_name='eventonovedad',
            name='contenido',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Contenido / Detalle'),
        ),
        migrations.AlterField(
            model_name='galeriamultimedia',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Descripción Corta'),
        ),
        migrations.AlterField(
            model_name='informacioninstitucional',
            name='chatbot_intro',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='Hola 👋 Soy el chatbot del Mirador Illari. ¿En qué puedo ayudarte?', verbose_name='Texto de bienvenida del chatbot'),
        ),
        migrations.AlterField(
            model_name='informacioninstitucional',
            name='chatbot_respuesta_predeterminada',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='Gracias por tu mensaje. Para más información puedes revisar las opciones rápidas o contactarnos por WhatsApp.', verbose_name='Respuesta predeterminada del chatbot'),
        ),
        migrations.AlterField(
            model_name='informacioninstitucional',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Descripción General'),
        ),
        migrations.AlterField(
            model_name='informacioninstitucional',
            name='historia',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Historia'),
        ),
        migrations.AlterField(
            model_name='informacioninstitucional',
            name='mision',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Misión'),
        ),
        migrations.AlterField(
            model_name='informacioninstitucional',
            name='proposito',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Propósito Institucional'),
        ),
        migrations.AlterField(
            model_name='informacioninstitucional',
            name='vision',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Visión'),
        ),
        migrations.AlterField(
            model_name='preguntafrecuente',
            name='pregunta',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Pregunta del Usuario'),
        ),
        migrations.AlterField(
            model_name='preguntafrecuente',
            name='respuesta',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Respuesta del Chatbot'),
        ),
        migrations.AlterField(
            model_name='servicioturistico',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='valor',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Descripción del Valor'),
        ),
    ]
