# Generated by Django 6.0.6 on 2026-07-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0021_alter_contenidoinicio_atractivo_1_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carruselinicio',
            name='imagen',
            field=models.ImageField(help_text='Tamaño recomendado: 1920 × 750 px. Mínimo permitido: 1600 × 625 px. Formatos permitidos: JPG, JPEG y PNG.', upload_to='carrusel/', verbose_name='Imagen de Fondo'),
        ),
    ]
