# Generated by Django 6.0.6 on 2026-07-18 19:47

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0022_alter_carruselinicio_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioturistico',
            name='disponibilidad',
            field=models.CharField(blank=True, help_text='Información opcional sobre fechas, horarios o disponibilidad del servicio.', max_length=200, null=True, verbose_name='Disponibilidad'),
        ),
        migrations.AddField(
            model_name='servicioturistico',
            name='incluye',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Incluye'),
        ),
        migrations.AddField(
            model_name='servicioturistico',
            name='precio_desde',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor aproximado cuando el precio varía según temporada o paquete.', max_digits=10, null=True, verbose_name='Precio Desde'),
        ),
        migrations.AddField(
            model_name='servicioturistico',
            name='precio_texto',
            field=models.CharField(blank=True, help_text="Texto opcional que describa el precio, por ejemplo 'Consultar precio' o 'Desde 120.00'.", max_length=200, null=True, verbose_name='Texto de precio'),
        ),
        migrations.AddField(
            model_name='servicioturistico',
            name='requiere_reserva',
            field=models.BooleanField(default=False, help_text='Marca si el servicio necesita reserva previa.', verbose_name='Requiere reserva'),
        ),
        migrations.AlterField(
            model_name='servicioturistico',
            name='precio_adulto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Adulto'),
        ),
    ]
