# Generated by Django 6.0.6 on 2026-07-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0023_servicioturistico_disponibilidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventonovedad',
            name='precio_texto',
            field=models.CharField(blank=True, help_text='Ejemplo: Incluido con la entrada, Desde $45, Gratuito, Consultar disponibilidad.', max_length=100, verbose_name='Precio'),
        ),
    ]
