# Generated by Django 6.0.6 on 2026-07-25 13:35

import django.db.models.deletion
import principal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0024_eventonovedad_precio_texto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='carruselinicio',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
        ),
        migrations.AlterField(
            model_name='carruselinicio',
            name='imagen',
            field=models.ImageField(help_text='Tamaño recomendado: 1000 × 1250 px. Utilice imágenes verticales con el elemento principal centrado. Formatos permitidos: JPG, JPEG y PNG.', upload_to='carrusel/', verbose_name='Imagen de Fondo'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
        ),
        migrations.AlterField(
            model_name='contenidoinicio',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
        ),
        migrations.AlterField(
            model_name='eventonovedad',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
        ),
        migrations.AlterField(
            model_name='eventonovedad',
            name='imagen',
            field=models.ImageField(upload_to='eventos/', validators=[principal.models.validate_public_image], verbose_name='Imagen publicitaria'),
        ),
        migrations.AlterField(
            model_name='eventonovedad',
            name='tipo',
            field=models.CharField(choices=[('Evento', 'Evento'), ('Novedad', 'Novedad')], max_length=100, verbose_name='Tipo de Aviso'),
        ),
        migrations.AlterField(
            model_name='galeriamultimedia',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
        ),
        migrations.AlterField(
            model_name='galeriamultimedia',
            name='imagen',
            field=models.ImageField(upload_to='galeria/', validators=[principal.models.validate_public_image], verbose_name='Archivo de imagen'),
        ),
        migrations.AlterField(
            model_name='informacioninstitucional',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
        ),
        migrations.AlterField(
            model_name='preguntafrecuente',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
        ),
        migrations.AlterField(
            model_name='servicioturistico',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
        ),
        migrations.AlterField(
            model_name='servicioturistico',
            name='imagen_principal',
            field=models.ImageField(upload_to='servicios/', validators=[principal.models.validate_public_image], verbose_name='Imagen principal'),
        ),
        migrations.AlterField(
            model_name='servicioturistico',
            name='tipo',
            field=models.CharField(choices=[('Atracciones', 'Atracciones'), ('Hospedaje', 'Hospedaje'), ('Gastronomía', 'Gastronomía'), ('Servicios Generales', 'Servicios Generales')], max_length=100, verbose_name='Tipo (Atracciones, Hospedaje, Gastronomía, Servicios Generales)'),
        ),
        migrations.AlterField(
            model_name='valor',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
        ),
    ]
