# Generated by Django 6.0.7 on 2026-08-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0025_alter_carruselinicio_id_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carruselinicio',
            name='imagen',
            field=models.ImageField(help_text='Tamaño recomendado: 1000 × 1250 px. Utilice imágenes verticales con el elemento principal centrado. Formatos permitidos: JPG, JPEG, PNG y WEBP.', upload_to='carrusel/', verbose_name='Imagen de Fondo'),
        ),
    ]
