# Generated by Django 6.0.7 on 2026-08-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0026_alter_carruselinicio_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidoinicio',
            name='atractivo_1_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='inicio/atractivos/', verbose_name='Imagen de Paisajes'),
        ),
        migrations.AddField(
            model_name='contenidoinicio',
            name='atractivo_2_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='inicio/atractivos/', verbose_name='Imagen de Aventura'),
        ),
        migrations.AddField(
            model_name='contenidoinicio',
            name='atractivo_3_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='inicio/atractivos/', verbose_name='Imagen de Cultura local'),
        ),
        migrations.AddField(
            model_name='contenidoinicio',
            name='atractivo_4_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='inicio/atractivos/', verbose_name='Imagen de Atención'),
        ),
    ]
