# Generated by Django 6.0.7 on 2026-08-22 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0027_contenidoinicio_atractivo_1_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='valores/', verbose_name='Imagen'),
        ),
    ]
