# Generated by Django 6.0.7 on 2026-08-22 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0028_valor_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valor',
            name='imagen',
        ),
    ]
