# Generated by Django 6.0.7 on 2026-09-19 02:19

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0029_remove_valor_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacioninstitucional',
            name='chatbot_intro',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='Hola, soy Jeyson, tu guía virtual del Mirador Illari. ¿En qué puedo ayudarte?', verbose_name='Texto de bienvenida del chatbot'),
        ),
    ]
